/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.sqlconexao;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ian-p
 */
public class Tela extends javax.swing.JFrame {

   Conexao db = new Conexao();
    
    public Tela() {
        initComponents();
        db.conecta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupo = new javax.swing.ButtonGroup();
        btnExibir = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        rbMedio = new javax.swing.JRadioButton();
        rbBaixo = new javax.swing.JRadioButton();
        rbAlto = new javax.swing.JRadioButton();
        txtPrioridade = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_tabela = new javax.swing.JTable();

        setTitle("ADE");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExibir.setText("Exibir");
        btnExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExibir, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 280, 72, -1));

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        getContentPane().add(btnInserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 280, -1, -1));

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, -1, -1));

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 16, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 272, -1, -1));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 13, 166, -1));

        jLabel3.setText("Descricao");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, -1, -1));

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 56, -1, 120));

        jLabel4.setText("Prioridade");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel5.setText("Pesquisar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 17, -1, -1));

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 14, 51, -1));

        btnPesquisar.setText("Ok");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 13, 401, -1));

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 280, -1, -1));

        rbMedio.setText("Baixo");
        getContentPane().add(rbMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, 20));

        rbBaixo.setText("Medio");
        getContentPane().add(rbBaixo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, 20));

        rbAlto.setText("Alto");
        getContentPane().add(rbAlto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, 20));
        getContentPane().add(txtPrioridade, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 70, -1));

        tbl_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Descricao", "Prioridade"
            }
        ));
        tbl_tabela.setToolTipText("");
        jScrollPane2.setViewportView(tbl_tabela);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 460, 110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirActionPerformed
    
            try{             
                    db.stm = db.con.createStatement(); 
                    ((DefaultTableModel)tbl_tabela.getModel()).setNumRows(0); 
                    tbl_tabela.updateUI(); 
                    db.rs = db.stm.executeQuery("Select * from tb_chamados"); 
                    while(db.rs.next()) { 
                    ((DefaultTableModel)tbl_tabela.getModel()).addRow(new Object[] {db.rs.getObject(1), 
                      db.rs.getObject(2),db.rs.getObject(3), db.rs.getObject(4), db.rs.getObject(5), db.rs.getObject(6)}); 
                    } 
           }catch(SQLException e){ //trata os erros SQL 
 
                    JOptionPane.showMessageDialog(this, "Erro Cmdo SQL " + e.getMessage() ); 
                } 
     
        
    }//GEN-LAST:event_btnExibirActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        
       
                         db.manipularSQL("insert into tb_chamados(nome,descricao,prioridade)values('"+txtNome.getText()+ "','" +txtDescricao.getText() + "','"+txtPrioridade.getText()+"');");

        
               //    db.manipularSQL("INSERT INTO tb_chamados(NOME,DESCRICAO, PRIORIDADE) values ('"+txtNome.getText()+ "','" +txtDescricao.getText()+ "','"+txtPrioridade.getText()+"');");

        
    }//GEN-LAST:event_btnInserirActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
         boolean consulta=true; 
            try{             
                    db.stm = db.con.createStatement(); 
                    if ("".equals(txtCodigo.getText())){ 
                        JOptionPane.showMessageDialog(null,"Digite um codigo..."); 
                        txtCodigo.requestFocus(); 
                    } 
                    else{ 
 
                        int ConsCodigo= Integer.parseInt(txtCodigo.getText()); 
 
                            db.rs = db.stm.executeQuery("Select * from tb_chamados where idchamado=" + ConsCodigo+";"); 
                            if(db.rs.next()){ 
                                txtNome.setText(db.rs.getString("Nome")); 
                                txtDescricao.setText(db.rs.getString("Descricao")); 
                                txtPrioridade.setText(db.rs.getString("Prioridade"));    
                                 btnAtualizar.setEnabled(true); 
                                 
                        } 
                        else 
                        { 
                            JOptionPane.showMessageDialog(null,"Codigo não encontrado..."); 
                        } 
               consulta=false; 
                        txtCodigo.requestFocus(); 
              } 
                    if (consulta) JOptionPane.showMessageDialog(this,"Dados Não Encontrados!"); 
                }catch( SQLException e){ //trata os erros SQL 
 
                    JOptionPane.showMessageDialog(this, "Registro não encontrado!\n" + e.getMessage() ); 
                }   
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed

        if ("".equals(txtCodigo.getText())){ 
                        JOptionPane.showMessageDialog(null,"Digite um codigo..."); 
                        txtCodigo.requestFocus(); 
        } 
        else{ 
           db.manipularSQL("UPDATE tb_chamados set Nome = '"+txtNome.getText()+ "',Descricao = '"+txtDescricao.getText()+ "' where idchamado= "+txtCodigo.getText()); 
            JOptionPane.showMessageDialog(null,"Registro alterado com sucesso!"); 
            
        }    
         
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
          db.manipularSQL("delete from tb_chamados where idchamado = " +txtCodigo.getText());
          JOptionPane.showMessageDialog(null, "Chamado deletado com sucesso"); 
    }//GEN-LAST:event_btnDeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnExibir;
    private javax.swing.ButtonGroup btnGrupo;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbAlto;
    private javax.swing.JRadioButton rbBaixo;
    private javax.swing.JRadioButton rbMedio;
    private javax.swing.JTable tbl_tabela;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPrioridade;
    // End of variables declaration//GEN-END:variables
}
